// Generated by gencpp from file assigment1/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ASSIGMENT1_MESSAGE_ADDTWOINTS_H
#define ASSIGMENT1_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <assigment1/AddTwoIntsRequest.h>
#include <assigment1/AddTwoIntsResponse.h>


namespace assigment1
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace assigment1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assigment1::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::assigment1::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::assigment1::AddTwoInts > {
  static const char* value()
  {
    return "assigment1/AddTwoInts";
  }

  static const char* value(const ::assigment1::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::assigment1::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::assigment1::AddTwoInts > 
template<>
struct MD5Sum< ::assigment1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assigment1::AddTwoInts >::value();
  }
  static const char* value(const ::assigment1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assigment1::AddTwoIntsRequest> should match 
// service_traits::DataType< ::assigment1::AddTwoInts > 
template<>
struct DataType< ::assigment1::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::assigment1::AddTwoInts >::value();
  }
  static const char* value(const ::assigment1::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assigment1::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::assigment1::AddTwoInts > 
template<>
struct MD5Sum< ::assigment1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assigment1::AddTwoInts >::value();
  }
  static const char* value(const ::assigment1::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assigment1::AddTwoIntsResponse> should match 
// service_traits::DataType< ::assigment1::AddTwoInts > 
template<>
struct DataType< ::assigment1::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::assigment1::AddTwoInts >::value();
  }
  static const char* value(const ::assigment1::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGMENT1_MESSAGE_ADDTWOINTS_H
