// Generated by gencpp from file assigment1/Circle.msg
// DO NOT EDIT!


#ifndef ASSIGMENT1_MESSAGE_CIRCLE_H
#define ASSIGMENT1_MESSAGE_CIRCLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assigment1
{
template <class ContainerAllocator>
struct Circle_
{
  typedef Circle_<ContainerAllocator> Type;

  Circle_()
    : x(0)
    , y(0)
    , radius(0)  {
    }
  Circle_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , radius(0)  {
  (void)_alloc;
    }



   typedef uint32_t _x_type;
  _x_type x;

   typedef uint32_t _y_type;
  _y_type y;

   typedef uint32_t _radius_type;
  _radius_type radius;





  typedef boost::shared_ptr< ::assigment1::Circle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assigment1::Circle_<ContainerAllocator> const> ConstPtr;

}; // struct Circle_

typedef ::assigment1::Circle_<std::allocator<void> > Circle;

typedef boost::shared_ptr< ::assigment1::Circle > CirclePtr;
typedef boost::shared_ptr< ::assigment1::Circle const> CircleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assigment1::Circle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assigment1::Circle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assigment1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'assigment1': ['/tmp/guest-zitp2n/ass1/src/assigment1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assigment1::Circle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assigment1::Circle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assigment1::Circle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assigment1::Circle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assigment1::Circle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assigment1::Circle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assigment1::Circle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9fe83ccd4927fa26ce122065a2ef1649";
  }

  static const char* value(const ::assigment1::Circle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9fe83ccd4927fa26ULL;
  static const uint64_t static_value2 = 0xce122065a2ef1649ULL;
};

template<class ContainerAllocator>
struct DataType< ::assigment1::Circle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assigment1/Circle";
  }

  static const char* value(const ::assigment1::Circle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assigment1::Circle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 x\n\
uint32 y\n\
uint32 radius\n\
\n\
";
  }

  static const char* value(const ::assigment1::Circle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assigment1::Circle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Circle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assigment1::Circle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assigment1::Circle_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.y);
    s << indent << "radius: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGMENT1_MESSAGE_CIRCLE_H
