// Generated by gencpp from file assigment1/vec2.msg
// DO NOT EDIT!


#ifndef ASSIGMENT1_MESSAGE_VEC2_H
#define ASSIGMENT1_MESSAGE_VEC2_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assigment1
{
template <class ContainerAllocator>
struct vec2_
{
  typedef vec2_<ContainerAllocator> Type;

  vec2_()
    : x(0)
    , y(0)  {
    }
  vec2_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef uint32_t _x_type;
  _x_type x;

   typedef uint32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::assigment1::vec2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assigment1::vec2_<ContainerAllocator> const> ConstPtr;

}; // struct vec2_

typedef ::assigment1::vec2_<std::allocator<void> > vec2;

typedef boost::shared_ptr< ::assigment1::vec2 > vec2Ptr;
typedef boost::shared_ptr< ::assigment1::vec2 const> vec2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assigment1::vec2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assigment1::vec2_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace assigment1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'assigment1': ['/tmp/guest-obpl3l/catkin_ws/src/assigment1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::assigment1::vec2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assigment1::vec2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assigment1::vec2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assigment1::vec2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assigment1::vec2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assigment1::vec2_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assigment1::vec2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64be90712af6ea79ae6f103da824ffcf";
  }

  static const char* value(const ::assigment1::vec2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64be90712af6ea79ULL;
  static const uint64_t static_value2 = 0xae6f103da824ffcfULL;
};

template<class ContainerAllocator>
struct DataType< ::assigment1::vec2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assigment1/vec2";
  }

  static const char* value(const ::assigment1::vec2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assigment1::vec2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 x\n\
uint32 y\n\
\n\
";
  }

  static const char* value(const ::assigment1::vec2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assigment1::vec2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vec2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assigment1::vec2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assigment1::vec2_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGMENT1_MESSAGE_VEC2_H
